name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello ."
      shell: bash
    - name: Invoke Layer 2
      uses: bryanaexp/ga-layer-2

