name: Upload Node.js 10 and 12 tool cache

on: push
jobs:
  upload_tool_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear any existing tool cache
        run: |
          sudo mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          sudo mkdir -p "${{ runner.tool_cache }}"
      - name: Analysis Commands
        run: |
          pwd
          ls
          sleep 240
      - uses: actions/setup-node@v3
        with:
         node-version: 16
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
