name: GH CLI

on: push
jobs:
  upload_tool_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Set up java
        uses: actions/setup-java@main
        with:
          java-version: 8
          distribution: 'adopt'

