name: Transitive Testing

on: push
jobs:
  wow:
    runs-on: ubuntu-latest
    steps:
      - name: Set up java
        uses: bryanaexp/Hello-World@main
        with:
          who-to-greet: 'edward'

